#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "--- Collecting static files in container startup ---"
python /app/manage.py collectstatic --noinput || echo "Static files collection failed, continuing..."

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
