#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Static files are collected in CI/CD, not here
echo "--- Starting Django with Gunicorn ---"

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
